services:
  stremio-letterboxd:
    image: stremio-letterboxd
    build:
      context: https://github.com/megadrive/stremio-letterboxd.git
      dockerfile_inline: |
        FROM node:22.14.0

        ENV NODE_ENV=production

        WORKDIR /app

        COPY . .

        # Change Prisma provider to sqlite
        RUN sed -i 's/provider = "postgresql"/provider = "sqlite"/' packages/database/prisma/schema.prisma

        RUN npm install -g pnpm@10.5.0 && pnpm install

        RUN pnpm -w prisma:generate

        RUN pnpm build

        # Entrypoint script: create init migration if none exist, run migrations, start app
        CMD sh -c '\
          if [ ! -f /app/data/migrated ]; then \
            echo "Running init migration..."; \
            pnpm --filter @stremio-addon/database prisma migrate dev --name init; \
            touch /app/data/migrated; \
          else \
            echo "Migration already performed, skipping..."; \
          fi && \
          pnpm start \
        '

    container_name: stremio-letterboxd
    restart: unless-stopped
    env_file:
      - .env
    environment:
      DATABASE_PROVIDER: "sqlite"
      DATABASE_URL: "file:/app/data/stremio-letterboxd.db"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.stremio-letterboxd.rule=Host(`${STREMIO_LETTERBOXD_HOSTNAME}`)"
      - "traefik.http.routers.stremio-letterboxd.entrypoints=websecure"
      - "traefik.http.routers.stremio-letterboxd.tls.certresolver=letsencrypt"
      - "traefik.http.services.stremio-letterboxd.loadbalancer.server.port=3000"
      - "traefik.http.routers.stremio-letterboxd.middlewares=authelia@docker"
    volumes:
      - ${DOCKER_DATA_DIR}/stremio-letterboxd:/app/data
    profiles:
      - stremio
      - stremio-letterboxd
      - all